# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Customer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, customer_id: str=None, first_name: str=None, last_name: str=None, phone_number: str=None, email: str=None):  # noqa: E501
        """Customer - a model defined in Swagger

        :param customer_id: The customer_id of this Customer.  # noqa: E501
        :type customer_id: str
        :param first_name: The first_name of this Customer.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this Customer.  # noqa: E501
        :type last_name: str
        :param phone_number: The phone_number of this Customer.  # noqa: E501
        :type phone_number: str
        :param email: The email of this Customer.  # noqa: E501
        :type email: str
        """
        self.swagger_types = {
            'customer_id': str,
            'first_name': str,
            'last_name': str,
            'phone_number': str,
            'email': str
        }

        self.attribute_map = {
            'customer_id': 'CustomerID',
            'first_name': 'FirstName',
            'last_name': 'LastName',
            'phone_number': 'PhoneNumber',
            'email': 'Email'
        }
        self._customer_id = customer_id
        self._first_name = first_name
        self._last_name = last_name
        self._phone_number = phone_number
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'Customer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Customer of this Customer.  # noqa: E501
        :rtype: Customer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def customer_id(self) -> str:
        """Gets the customer_id of this Customer.


        :return: The customer_id of this Customer.
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: str):
        """Sets the customer_id of this Customer.


        :param customer_id: The customer_id of this Customer.
        :type customer_id: str
        """

        self._customer_id = customer_id

    @property
    def first_name(self) -> str:
        """Gets the first_name of this Customer.


        :return: The first_name of this Customer.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this Customer.


        :param first_name: The first_name of this Customer.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this Customer.


        :return: The last_name of this Customer.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this Customer.


        :param last_name: The last_name of this Customer.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def phone_number(self) -> str:
        """Gets the phone_number of this Customer.


        :return: The phone_number of this Customer.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: str):
        """Sets the phone_number of this Customer.


        :param phone_number: The phone_number of this Customer.
        :type phone_number: str
        """

        self._phone_number = phone_number

    @property
    def email(self) -> str:
        """Gets the email of this Customer.


        :return: The email of this Customer.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Customer.


        :param email: The email of this Customer.
        :type email: str
        """

        self._email = email
