# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ScanningSession(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, session_id: str=None, super_market_id: str=None, status: str=None, date_time: str=None, scanned_item_id: str=None):  # noqa: E501
        """ScanningSession - a model defined in Swagger

        :param session_id: The session_id of this ScanningSession.  # noqa: E501
        :type session_id: str
        :param super_market_id: The super_market_id of this ScanningSession.  # noqa: E501
        :type super_market_id: str
        :param status: The status of this ScanningSession.  # noqa: E501
        :type status: str
        :param date_time: The date_time of this ScanningSession.  # noqa: E501
        :type date_time: str
        :param scanned_item_id: The scanned_item_id of this ScanningSession.  # noqa: E501
        :type scanned_item_id: str
        """
        self.swagger_types = {
            'session_id': str,
            'super_market_id': str,
            'status': str,
            'date_time': str,
            'scanned_item_id': str
        }

        self.attribute_map = {
            'session_id': 'SessionID',
            'super_market_id': 'SuperMarketID',
            'status': 'Status',
            'date_time': 'DateTime',
            'scanned_item_id': 'ScannedItemID'
        }
        self._session_id = session_id
        self._super_market_id = super_market_id
        self._status = status
        self._date_time = date_time
        self._scanned_item_id = scanned_item_id

    @classmethod
    def from_dict(cls, dikt) -> 'ScanningSession':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScanningSession of this ScanningSession.  # noqa: E501
        :rtype: ScanningSession
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this ScanningSession.


        :return: The session_id of this ScanningSession.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this ScanningSession.


        :param session_id: The session_id of this ScanningSession.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def super_market_id(self) -> str:
        """Gets the super_market_id of this ScanningSession.


        :return: The super_market_id of this ScanningSession.
        :rtype: str
        """
        return self._super_market_id

    @super_market_id.setter
    def super_market_id(self, super_market_id: str):
        """Sets the super_market_id of this ScanningSession.


        :param super_market_id: The super_market_id of this ScanningSession.
        :type super_market_id: str
        """

        self._super_market_id = super_market_id

    @property
    def status(self) -> str:
        """Gets the status of this ScanningSession.


        :return: The status of this ScanningSession.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ScanningSession.


        :param status: The status of this ScanningSession.
        :type status: str
        """

        self._status = status

    @property
    def date_time(self) -> str:
        """Gets the date_time of this ScanningSession.


        :return: The date_time of this ScanningSession.
        :rtype: str
        """
        return self._date_time

    @date_time.setter
    def date_time(self, date_time: str):
        """Sets the date_time of this ScanningSession.


        :param date_time: The date_time of this ScanningSession.
        :type date_time: str
        """

        self._date_time = date_time

    @property
    def scanned_item_id(self) -> str:
        """Gets the scanned_item_id of this ScanningSession.


        :return: The scanned_item_id of this ScanningSession.
        :rtype: str
        """
        return self._scanned_item_id

    @scanned_item_id.setter
    def scanned_item_id(self, scanned_item_id: str):
        """Sets the scanned_item_id of this ScanningSession.


        :param scanned_item_id: The scanned_item_id of this ScanningSession.
        :type scanned_item_id: str
        """

        self._scanned_item_id = scanned_item_id
