# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SupermarketLocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, line1: str=None, city: str=None, province: str=None, zip_code: str=None):  # noqa: E501
        """SupermarketLocation - a model defined in Swagger

        :param line1: The line1 of this SupermarketLocation.  # noqa: E501
        :type line1: str
        :param city: The city of this SupermarketLocation.  # noqa: E501
        :type city: str
        :param province: The province of this SupermarketLocation.  # noqa: E501
        :type province: str
        :param zip_code: The zip_code of this SupermarketLocation.  # noqa: E501
        :type zip_code: str
        """
        self.swagger_types = {
            'line1': str,
            'city': str,
            'province': str,
            'zip_code': str
        }

        self.attribute_map = {
            'line1': 'line1',
            'city': 'city',
            'province': 'province',
            'zip_code': 'zipCode'
        }
        self._line1 = line1
        self._city = city
        self._province = province
        self._zip_code = zip_code

    @classmethod
    def from_dict(cls, dikt) -> 'SupermarketLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Supermarket_Location of this SupermarketLocation.  # noqa: E501
        :rtype: SupermarketLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def line1(self) -> str:
        """Gets the line1 of this SupermarketLocation.


        :return: The line1 of this SupermarketLocation.
        :rtype: str
        """
        return self._line1

    @line1.setter
    def line1(self, line1: str):
        """Sets the line1 of this SupermarketLocation.


        :param line1: The line1 of this SupermarketLocation.
        :type line1: str
        """

        self._line1 = line1

    @property
    def city(self) -> str:
        """Gets the city of this SupermarketLocation.


        :return: The city of this SupermarketLocation.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this SupermarketLocation.


        :param city: The city of this SupermarketLocation.
        :type city: str
        """

        self._city = city

    @property
    def province(self) -> str:
        """Gets the province of this SupermarketLocation.

        2 Letter province Code  # noqa: E501

        :return: The province of this SupermarketLocation.
        :rtype: str
        """
        return self._province

    @province.setter
    def province(self, province: str):
        """Sets the province of this SupermarketLocation.

        2 Letter province Code  # noqa: E501

        :param province: The province of this SupermarketLocation.
        :type province: str
        """
        allowed_values = ["AB", "BC", "MB", "NB", "NL", "NS", "NT", "NU", "ON", "PE", "QC", "SK", "YT"]  # noqa: E501
        if province not in allowed_values:
            raise ValueError(
                "Invalid value for `province` ({0}), must be one of {1}"
                .format(province, allowed_values)
            )

        self._province = province

    @property
    def zip_code(self) -> str:
        """Gets the zip_code of this SupermarketLocation.


        :return: The zip_code of this SupermarketLocation.
        :rtype: str
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code: str):
        """Sets the zip_code of this SupermarketLocation.


        :param zip_code: The zip_code of this SupermarketLocation.
        :type zip_code: str
        """

        self._zip_code = zip_code
