# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.supermarket_location import SupermarketLocation  # noqa: F401,E501
from swagger_server import util


class Supermarket(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, supermarket_id: str=None, name: str=None, location: SupermarketLocation=None):  # noqa: E501
        """Supermarket - a model defined in Swagger

        :param supermarket_id: The supermarket_id of this Supermarket.  # noqa: E501
        :type supermarket_id: str
        :param name: The name of this Supermarket.  # noqa: E501
        :type name: str
        :param location: The location of this Supermarket.  # noqa: E501
        :type location: SupermarketLocation
        """
        self.swagger_types = {
            'supermarket_id': str,
            'name': str,
            'location': SupermarketLocation
        }

        self.attribute_map = {
            'supermarket_id': 'SupermarketID',
            'name': 'Name',
            'location': 'Location'
        }
        self._supermarket_id = supermarket_id
        self._name = name
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'Supermarket':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Supermarket of this Supermarket.  # noqa: E501
        :rtype: Supermarket
        """
        return util.deserialize_model(dikt, cls)

    @property
    def supermarket_id(self) -> str:
        """Gets the supermarket_id of this Supermarket.


        :return: The supermarket_id of this Supermarket.
        :rtype: str
        """
        return self._supermarket_id

    @supermarket_id.setter
    def supermarket_id(self, supermarket_id: str):
        """Sets the supermarket_id of this Supermarket.


        :param supermarket_id: The supermarket_id of this Supermarket.
        :type supermarket_id: str
        """

        self._supermarket_id = supermarket_id

    @property
    def name(self) -> str:
        """Gets the name of this Supermarket.


        :return: The name of this Supermarket.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Supermarket.


        :param name: The name of this Supermarket.
        :type name: str
        """

        self._name = name

    @property
    def location(self) -> SupermarketLocation:
        """Gets the location of this Supermarket.


        :return: The location of this Supermarket.
        :rtype: SupermarketLocation
        """
        return self._location

    @location.setter
    def location(self, location: SupermarketLocation):
        """Sets the location of this Supermarket.


        :param location: The location of this Supermarket.
        :type location: SupermarketLocation
        """

        self._location = location
